name: netsells_flutter_analysis
version: 3.0.0
description: Static analysis rules for Dart and Flutter used at Netsells
repository: https://github.com/netsells/flutter-analysis
issue_tracker: https://github.com/netsells/flutter-analysis
homepage: https://github.com/netsells/flutter-analysis
documentation: https://github.com/netsells/flutter-analysis

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dart_code_metrics: ^4.15.2
